# Generated by Django 3.2 on 2026-06-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_DE_PAGO', 'Pendiente de pago'), ('PAGADO', 'Pagado'), ('EN_USO', 'En uso'), ('DEVUELTO', 'Devuelto'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_DE_PAGO', max_length=20),
        ),
    ]
