# Generated by Django 3.2.20 on 2024-11-21 12:57

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_id_alter_orderproduct_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='fecha_fin',
            field=models.DateField(default=orders.models.get_default_end_date),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='fecha_inicio',
            field=models.DateField(default=orders.models.get_default_start_date),
        ),
    ]
