# Generated by Django 3.2.20 on 2024-11-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
        ('orders', '0005_auto_20241121_1357'),
    ]

    operations = [
    ]
