# Generated by Django 3.2.20 on 2024-11-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente de pago', 'Pendiente de pago'), ('En uso', 'En uso'), ('Devuelto', 'Devuelto')], default='New', max_length=50),
        ),
    ]
