# Generated by Django 3.2.20 on 2024-11-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_combustible',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
