# Generated by Django 3.2.20 on 2024-12-06 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20241206_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.fabricante'),
        ),
        migrations.AlterField(
            model_name='product',
            name='puerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.puerto'),
        ),
    ]
